# Generated by Django 3.0.6 on 2020-05-24 22:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=1255)),
                ('message_post_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thread_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('thread_message', models.TextField(max_length=1255)),
                ('thread_post_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Thread',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('forum_post', models.TextField(max_length=1255)),
                ('forum_post_time', models.DateTimeField(auto_now_add=True)),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmzoneweb.Thread')),
            ],
            options={
                'db_table': 'Forum',
            },
        ),
    ]
