# Generated by Django 3.0.7 on 2020-06-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ad_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='ad_images/default.png', upload_to='ad_images', verbose_name='Ad Image'),
        ),
    ]
